install.packages("BGLR")
install.packages("BayesTree")
install.packages("torch")
install.packages('luz')
install.packages('corpcor')
install.packages("INLA", repos=c(getOption("repos"),  INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)
